Repository bitcoin-sv/spv-wallet-js-client, pull requests merged in 2024-04, with the labels that each got.

#900 fix(BUX-644): handle paymail key derivation
  src/client.ts
  src/types.ts
Labels: tested

#905 refactor(BUX-611) codebase improvements
  .prettierrc
  .prettierrc.cjs
  src/authentication.ts
  src/client.ts
  src/errors.ts
  src/httpclient.ts
  src/index.test.ts
  src/index.ts
  src/logger.ts
  src/types.ts
  src/utils/index.test.ts
  src/utils/index.ts
  src/utils/keys.test.ts
  src/utils/keys.ts
  src/utils/sign.ts
Labels: tested

#914 feat(BUX-614) examples
  examples/README.md
  examples/admin-add-user.ts
  examples/admin-remove-user.ts
  examples/create-transaction.ts
  examples/example-keys.ts
  examples/generate-keys.ts
  examples/get-balance.ts
  examples/list-transactions.ts
  examples/package.json
  examples/send-op-return.ts
  examples/tsconfig.json
  src/client.ts
  tsconfig.json
Labels: tested

#910 feat(BUX-593): unify branch names
  .github/mergify.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/sync-labels.yml
  .github/workflows/test.yml
  README.md
Labels: tested

#916 feat(BUX-714): README with additional examples
  README.md
  examples/README.md
  examples/custom-logger.ts
  examples/handle-exceptions.ts
  examples/package.json
Labels: feature, tested

#903 feat(BUX-705): added gitbook
  README.md
Labels: tested

#919 feat: version bump
  package.json
Labels: tested

#932 feat(SPV-710): replace bsv.js with ts-sdk
  examples/create-transaction.ts
  package.json
  src/authentication.ts
  src/client.ts
  src/errors.ts
  src/httpclient.ts
  src/index.test.ts
  src/types.ts
  src/utils/index.test.ts
  src/utils/index.ts
  src/utils/keys.test.ts
  src/utils/keys.ts
  src/utils/sign.test.ts
  src/utils/sign.ts
  yarn.lock
Labels: feature, chore, tested
