Repository bitcoin-sv/spv-wallet-js-client, pull requests merged in 2024-06, with the labels that each got.

#983 updating packages version
  package.json
  yarn.lock
Labels: tested

#997 feat(SPV-869): changed global to globalThis
  package.json
  src/httpclient.ts
Labels: bug-P2, tested

#1000 chore(SPV-xxx): bump version
  package.json
Labels: tested

#1002 feat(SPV-000): bump ts-sdk version and gitignore on .vscode dir
  .gitignore
  package.json
  yarn.lock
Labels: tested

#955 feat(SPV-730) TOTP and Contacts support
  examples/README.md
  examples/generate-totp.ts
  examples/package.json
  package.json
  src/client.ts
  src/errors.ts
  src/index.test.ts
  src/totp/converters.ts
  src/totp/index.ts
  src/totp/pike-totp.test.ts
  src/totp/pike-totp.ts
  src/totp/sha1hmac.ts
  src/totp/totp.test.ts
  src/totp/totp.ts
Labels: feature, tested

#1003 fix(SPV-000): releaser
  .github/workflows/release.yml
  package.json
Labels: tested

#1005 fix(SPV-000): release with no 'debug' flag
  .github/workflows/release.yml
  package.json
Labels: tested

#1006 fix(SPV-XXX): downgrade version of used goreleaser
  .github/workflows/release.yml
  package.json
Labels: tested

#1007 feat(SPV-XXX): bump node version
  package.json
Labels: chore, tested

#1001 fix(SPV-872): fix utils imports and minor issues
  examples/admin-add-user.ts
  examples/admin-remove-user.ts
  examples/create-transaction.ts
  examples/get-balance.ts
  examples/handle-exceptions.ts
  examples/list-transactions.ts
  examples/send-op-return.ts
Labels: tested

#1011 feat(SPV-886): switch to TOTP algorithm from ts-sdk
  package.json
  src/totp/converters.ts
  src/totp/pike-totp.ts
  src/totp/sha1hmac.ts
  src/totp/totp.test.ts
  src/totp/totp.ts
Labels: tested
