Repository bitcoin-sv/spv-wallet-js-client, pull requests merged in 2024-02, with the labels that each got.

#833 fix(BUX-557): fix OP_RETURN tx issue
  src/index.ts
Labels: bug-P3

#834 chore(000): use node v20 in workflows
  .github/workflows/release.yml
Labels: update

#835 chore: bump ver to 1.5.0
  package.json
Labels: update

#848 refactor: use template literals tests instead of array for each
  src/index.test.ts
Labels: test

#844 fix(BUX-575): connection to server issue
  package.json
  src/index.test.ts
  src/index.ts
  src/transports/http.ts
  yarn.lock
Labels: bug-P3

#851 BUX-589/migrate package
  .all-contributorsrc
  .github/CODEOWNERS
  .github/CODE_STANDARDS.md
  .github/FUNDING.yml
  .github/IMAGES/share-image.png
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  .goreleaser.yml
  LICENSE
  Makefile
  README.md
  jsdoc.json
  package.json
  src/authentication.ts
  src/index.test.ts
  src/index.ts
  src/interface.ts
  src/logger/index.ts
  yarn.lock
Labels: tested

#864 feat(BUX-585): use official bsv scope of package; remove contributors from package.json
  package.json
Labels: tested

#865 chore(BUX-585): start versions from 0.1.0
  package.json
Labels: tested

#867 fix: back to global.fetch
  package.json
  src/index.test.ts
  src/transports/http.ts
  yarn.lock
Labels: bug-P3, tested

#872 fix: errors from http requests are not populated
  package.json
  src/transports/http.ts
Labels: tested
