Repository bitcoin-sv/spv-wallet-js-client, pull requests merged in 2024-12, with the labels that each got.

#1110 Fix(spv 1222) tslib issue with vanilla js project
  package.json
  rollup.config.ts
  tsconfig.json
Labels: chore, tested

#1112 Fix(spv 1222) tslib issue with vanilla js project #2
  package.json
  rollup.config.ts
Labels: bug-P2, tested

#1117 ci(SPV-1271): trigger regression test workflow
  .github/workflows/trigger-regression-tests.yml
Labels: tested

#1115 feat(SPV-1225): add admin confirmation for contacts
  src/client.ts
Labels: tested

#1120 feat(SPV-1296): add js-client method to call newly create contact admin method
  src/client.ts
  src/index.test.ts
  src/types.ts
Labels: feature, tested

#1122 feat(SPV-1214): add admin contact filter to retreive contacts by xpub_id
  src/client.ts
  src/filters.ts
Labels: tested

#1123 feat(SPV-1320): fix contacts model
  package.json
  src/types.ts
Labels: tested
