Repository bitcoin-sv/spv-wallet-js-client, pull requests merged in 2025-01, with the labels that each got.

#1126 feat!(SPV-1288): js client new admin api
  src/client.ts
  src/index.test.ts
  src/regression_tests/regression_test.test.ts
  src/regression_tests/utils.ts
  src/types.ts
Labels: tested

#1129 feat(SPV-1348): add missing regression tests label
  .github/labels.yml
Labels: chore, tested

#1128 feat(SPV-1263): add endpoint for list of paymails
  src/client.ts
  src/filters.ts
Labels: tested

#1101 fix(SPV-1146): test metadata query with one not-working case
  src/query/query-builder.test.ts
  src/query/query-builder.ts
Labels: tested

#1133 feat(SPV-1366): correct return models from api
  examples/admin-remove-user.ts
  src/client.ts
  src/types.ts
Labels: tested, regression-tests

#1134 deps(XXX): bump to beta 29
  package.json
Labels: tested

#1135 feat(spv-1377): fix query params
  examples/list-transactions.ts
  package.json
  src/client.ts
  src/query/query-builder.test.ts
  src/query/query-builder.ts
  src/regression_tests/utils.ts
  src/types.ts
Labels: tested, regression-tests

#1137 feat(SPV-1341): apply changes to delete paymail
  examples/admin-remove-user.ts
  src/client.ts
  src/index.test.ts
  src/regression_tests/regression_test.test.ts
  src/regression_tests/utils.ts
Labels: tested, regression-tests

#1139 feat(SPV-1405): the new way of generating&validating TOTP - fixes&improvements for example
  examples/generate-totp.ts
  examples/manage-contacts.ts
  examples/package.json
  src/client.ts
  src/totp/pike-totp.ts
Labels: tested
